### ISSUE TITLE
Support clues and boss killcount

### ISSUE THREAD

**Issue by AdamKBeck** [Chasesc/OSRS-API-Wrapper#3]
There's been more categories on the hiscores. Any plans to update this wrapper?

**Comment by Chasesc** [comment]
Hi Adam, I have added support in the latest commit. 

Hiscores objects now have self.bosses and self.minigames with this data:

![image](https://user-images.githubusercontent.com/8884324/71770683-80291100-2efd-11ea-880d-222c39fbacfa.png)

There are still a few bosses that are missing. Comparing the api response with the hiscores page could be done, but I got too lazy to do them all lol.

These instances are labeled as const.UNUSED_OR_UNKNOWN and are not included in the mappings.

**Comment by AdamKBeck** [comment]
Thanks for the quick turnaround. Other than the missing bosses, do you have any other features that need to be added?

**Comment by Chasesc** [comment]
As far as I know, there is no official items API. We currently get the list of all items in the game from `items_osrs.json`. This file is a few years old now, so new items are not included. It would be nice if we had a better way to update this file, possibly automatically. I haven't done much research in this area.

In addition, if https://oldschool.runescape.wiki/ has some API, it would be nice to integrate into this repo. This could help with https://github.com/Chasesc/OSRS-API-Wrapper/issues/2

If you have any additional ideas, feel free to open a PR or comment them here.

**Comment by AdamKBeck** [comment]
From the runescape wiki discord: 

```
we don't do anything special with GE prices other than the median price that Jagex reports. you could use the osbuddy API for that
you can get a list of ALL items from the game cache, or a lot of other places
```

**Comment by AdamKBeck** [comment]
For twisted league I wrote a quick script to get the maximum total xp to see if there were any hidden people on the hiscores that haven't maxed yet. I wanted to make more crawlers to see momentum within the leagues to predict the final points people will end at.

I'm not sure if this is a separate project, or if you think it could be part of a PR for this project.

**Comment by Chasesc** [comment]
> For twisted league I wrote a quick script to get the maximum total xp to see if there were any hidden people on the hiscores that haven't maxed yet. I wanted to make more crawlers to see momentum within the leagues to predict the final points people will end at.
> 
> I'm not sure if this is a separate project, or if you think it could be part of a PR for this project.

Does it add any new functionality to the API? If so, those could be merged in.

If it is simple enough to follow quickly, it could be useful to put it in an examples directory.
