### ISSUE TITLE
Consider making a release and put it on PyPi

### ISSUE THREAD

**Issue by PureTryOut** [Chasesc/OSRS-API-Wrapper#5]
Hey, I'd love to use this library in a possible project of mine (I can't find any other Python libraries for the API anyway), but to do so I'd like to install this from PyPi (`pip install osrs-api-wrapper` or something like that). Could you make a release and upload it on there?

**Comment by Chasesc** [comment]
Great idea. I can do this later when I have some time.

**Comment by Chasesc** [comment]
The initial release is now live at https://pypi.org/project/python-osrsapi/
